{% set name = "FileSenderCLI" %}
{% set version = "3.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ./src

build:
  number: 0
  noarch: python
  script:
    - PYTHONDONTWRITEBYTECODE="" {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - python
    - pip
    - setuptools >58.2.0
    - wheel
  host:
    - python
    - pip
    - setuptools >58.2.0
    - wheel
    - requests
    - urllib3
    - cryptography
  run:
    - python
    - requests
    - urllib3
    - cryptography

test:
  imports:
    - filesender
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.aarnet.edu.au/filesender
  license: BSD
  license_family: BSD
  summary: CLI tool for FileSender

