{% set name = "FileSenderCLI" %}
{% set version = "3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ./src

build:
  noarch: python
  number: 0
  script:
    - "mkdir -p $PREFIX/bin"
    - "cp filesender.py $PREFIX/bin/filesender.py"
    - "chmod 777 $PREFIX/bin/filesender.py"

requirements:
  build:
    - pip
    - python
  host:
    - pip
    - python
  run:
    - python
    - conda-forge::requests
    - conda-forge::urllib3
    - conda-forge::cryptography

about:
  home: https://www.aarnet.edu.au/filesender
  license: BSD
  license_family: BSD
  summary: CLI tool for FileSender

