{% set name = "FileSenderCLI" %}
{% set version = "3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

requirements:
  host:
    - pip
    - python
  run:
    - python

source:
  path: ./src

build:
  noarch: python
  number: 0
  script:
    - "{{ PYTHON }} -m pip install requests urllib3 cryptography -vv"
    - "mkdir -p $PREFIX/bin"
    - "cp filesender.py $PREFIX/bin/filesender.py"
    - "chmod 777 $PREFIX/bin/filesender.py"

about:
  home: https://www.aarnet.edu.au/filesender
  license: BSD
  license_family: BSD
  summary: CLI tool for FileSender

