{% set name = "FileSenderCLI" %}
{% set version = "3.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ./src

build:
  noarch: python
  number: 0
  script:
    - echo "START PIP -----------------------------------"
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - echo "END PIP -------------------------------------"

requirements:
  host:
    - python
    - pip
    - setuptools >58.2.0
    - wheel
  run:
    - python
    - requests
    - urllib3
    - cryptography

test:
  imports:
    - filesender
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.aarnet.edu.au/filesender
  license: BSD
  license_family: BSD
  summary: CLI tool for FileSender

