{% set name = "FileSenderCLI" %}
{% set version = "3.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ./src

build:
  noarch: python
  number: 0
  script:
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

about:
  home: https://www.aarnet.edu.au/filesender
  license: BSD
  license_family: BSD
  summary: CLI tool for FileSender

